### ISSUE TITLE
[12.0] TypeError: Model 'base.config.settings' does not exist in registry.

### ISSUE THREAD

**Issue by ichdamola** [coopiteasy/vertical-cooperative#118]
#### I got the following error while installing the "Easy My Coop" module.

~~~markdown
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/opt/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 419, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo/odoo/modules/loading.py", line 311, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo/odoo/modules/loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
  File "/opt/odoo/odoo/modules/registry.py", line 241, in load
    model = cls._build_model(self, cr)
  File "/opt/odoo/odoo/models.py", line 439, in _build_model
    raise TypeError("Model %r does not exist in registry." % name)
TypeError: Model 'base.config.settings' does not exist in registry.
~~~

**Comment by ichdamola** [comment]
### To reproduce the error, clone the [module repo](https://github.com/coopiteasy/vertical-cooperative/tree/12.0/easy_my_coop) into the local-addons folder of Odoo 12, and try to install it, having set debug=true and update app.
![1](https://user-images.githubusercontent.com/20647487/90439023-c6b62f00-e0cc-11ea-89b2-cda04d246937.png)
![2](https://user-images.githubusercontent.com/20647487/90439054-cd44a680-e0cc-11ea-8584-b64e9534743d.png)

**Comment by robinkeunen** [comment]
Hi @adedamola-ad , I can install from scratch at home. Are you sure you configured the addons-path right? It should look like:

```
addons_path =
    /home/odoo12/odoo/odoo/addons,
    /home/odoo12/odoo/addons,
    /home/odoo12/vertical-cooperative
...
```
