### ISSUE TITLE
Fix test matrix for cooperator and dependencies

### ISSUE THREAD

**Issue by robinkeunen** [coopiteasy/vertical-cooperative#290]
I encountered module incompatibilities in vertical-cooperative tests, il you run 

1) -i easy_my_coop_api 

=> it passes

2) -i easy_my_coop_api --test-enable

=> fails because of missing record: Exception: Cannot update missing record 'easy_my_coop.subscription_journal'

3) -i easy_my_coop,easy_my_coop_api --test-enable

=> fails because of field from emc_api accessed from emc

2021-12-16 13:35:32,510 52195 ERROR emc-test odoo.addons.easy_my_coop.tests.test_emc: ` ValueError: Invalid field 'external_id_generated' in leaf "<osv.ExtendedLeaf: ('external_id_generated', '=', False) on subscription_request (ctx: )>"

4) -i easy_my_coop_api --test-enable

=> passes

Intuition:

When loading test account data, it deletes some of the loaded data such as subscription_journal. This results in missing xml_id accessed in test code or demo data if emc.binding.internal_id is set with ondelete='cascade' or breaks not null constraint if the field is left with default ondelete='set null'.

The second install of easy_my_coop reinstalls the missing data (the subscription journal).

Probably here: self.chart.try_loading_for_current_company()

**Comment by carmenbianca** [comment]
Encountered approximately this issue, but with updating instead of testing.

`cooperator_api` cannot be updated if `cooperator` is not updated at least once.

### Steps to reproduce

1. On faba671d460cfb41dc0d431fa2ce67956fafa4eb (12.0-komunigi at time of writing), install `cooperator_api` on a fresh database.
2. Restart Odoo with `-u cooperator_api`. This fails.
3. Try again with `-u cooperator,cooperator_api`. This works.
4. Try again with `-u cooperator_api`. This works.

### Traceback

Result from step 2.

```
2022-04-01 08:12:35,115 2070021 INFO 12-komunigi-api2 odoo.modules.loading: loading cooperator_api/demo/demo.xml 
2022-04-01 08:12:35,131 2070021 WARNING 12-komunigi-api2 odoo.modules.loading: Module cooperator_api demo data failed to install, installed without demo data 
Traceback (most recent call last):
  File "/var/home/coopiteasy/cie/komunigi/src/odoo/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/var/home/coopiteasy/cie/komunigi/src/odoo/odoo/tools/convert.py", line 613, in _tag_record
    raise Exception("Cannot update missing record %r" % xid)
Exception: Cannot update missing record 'cooperator.subscription_journal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/home/coopiteasy/cie/komunigi/src/odoo/odoo/modules/loading.py", line 84, in load_demo
    load_data(cr, idref, mode, kind='demo', package=package, report=report)
  File "/var/home/coopiteasy/cie/komunigi/src/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/var/home/coopiteasy/cie/komunigi/src/odoo/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/var/home/coopiteasy/cie/komunigi/src/odoo/odoo/tools/convert.py", line 865, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/var/home/coopiteasy/cie/komunigi/src/odoo/odoo/tools/convert.py", line 764, in parse
    exc_info[2]
  File "/var/home/coopiteasy/cie/komunigi/src/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/var/home/coopiteasy/cie/komunigi/src/odoo/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/var/home/coopiteasy/cie/komunigi/src/odoo/odoo/tools/convert.py", line 613, in _tag_record
    raise Exception("Cannot update missing record %r" % xid)
odoo.tools.convert.ParseError: "Cannot update missing record 'cooperator.subscription_journal'" while parsing /var/home/coopiteasy/cie/komunigi/src/coopiteasy/vertical-cooperative/cooperator_api/demo/demo.xml:33, near
<record id="cooperator.subscription_journal" model="account.journal">
        <field name="_api_external_id">1</field>
        <field name="external_id_generated" eval="True"/>
    </record>
```

---

Not entirely sure what's going on.

**Comment by robinkeunen** [comment]
This has nothing to do with `cooperator_api` :

- install `cooperator` on new database
- query database, no subscription journal exists:

```sql
robinkeunen@/tmp:cooperator> select *
 from ir_model_data
 where module = 'cooperator'
   and model = 'account.journal'
+----+------------+-------------+------------+-----------+----------+------+-----------+-------------+--------+-------+--------+
| id | create_uid | create_date | write_date | write_uid | noupdate | name | date_init | date_update | module | model | res_id |
|----+------------+-------------+------------+-----------+----------+------+-----------+-------------+--------+-------+--------|
+----+------------+-------------+------------+-----------+----------+------+-----------+-------------+--------+-------+--------+
SELECT 0
Time: 0.018s
```
- install `cooperator` again

=> it is now in database


Not sure where to start... It seems that something deletes the journal on the first initialisation.

**Comment by robinkeunen** [comment]
Definitely here ? When initialising the database, odoo executes this : 

```py
    def try_loading_for_current_company(self):
        """ Installs this chart of accounts for the current company if not chart
        of accounts had been created for it yet.
        """
...
        # If we don't have any chart of account on this company, install this chart of account
        if not company.chart_template_id and not self.existing_accounting(company):
            self.load_for_current_company(15.0, 15.0)

    def load_for_current_company(self, sale_tax_rate, purchase_tax_rate):
        """ Installs this chart of accounts on the current company, replacing
        the existing one if it had already one defined. If some accounting entries
        had already been made, this function fails instead, triggering a UserError.

        Also, note that this function can only be run by someone with administration
        rights.
        """
...
            existing_accounts = self.env['account.account'].search([('company_id', '=', company.id)]).  # <--- ['Equity', 'Cooperators']
        if existing_accounts:
            # we tolerate switching from accounting package (localization module) as long as there isn't yet any accounting
            # entries created for the company.
            if self.existing_accounting(company):
                raise UserError(_('Could not install new chart of account as there are already accounting entries existing.'))

            # delete accounting properties
            prop_values = ['account.account,%s' % (account_id,) for account_id in existing_accounts.ids]
            existing_journals = self.env['account.journal'].search([('company_id', '=', company.id)])
            if existing_journals:   #  <---  existing_journals.name = 'Subscription Journal'
                prop_values.extend(['account.journal,%s' % (journal_id,) for journal_id in existing_journals.ids])
            accounting_props = self.env['ir.property'].search([('value_reference', 'in', prop_values)]).
            if accounting_props:  # accounting_props = None
                accounting_props.sudo().unlink()

            # delete account, journal, tax, fiscal position and reconciliation model
            models_to_delete = ['account.reconcile.model', 'account.fiscal.position', 'account.tax', 'account.move', 'account.journal']
            for model in models_to_delete:  # model = 'account.journal'
                res = self.env[model].search([('company_id', '=', company.id)])  # res : account.journal(1) => subscription.journal
                if len(res):
                    res.unlink()  # => gone
            existing_accounts.unlink()
```

We have to understand how to either protect the accounting demo data or load it after this function is executed.

**Comment by victor-champonnois** [comment]
closed in favor of https://github.com/OCA/cooperative/issues/25
