### ISSUE TITLE
As a cooperator user, I cannot add a share subscription to a cooperator

### ISSUE THREAD

**Issue by robinkeunen** [coopiteasy/vertical-cooperative#297]
```log
Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "/home/komunigi/src/odoo/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 600

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/komunigi/src/odoo/odoo/fields.py", line 1064, in __get__
    value = record.env.cache.get(record, self)
  File "/home/komunigi/src/odoo/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('subscription.request(600,).name', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/komunigi/src/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/komunigi/src/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/komunigi/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/komunigi/src/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/home/komunigi/src/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/komunigi/src/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/komunigi/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/komunigi/src/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/komunigi/src/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/komunigi/src/odoo/addons/web/controllers/main.py", line 971, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/komunigi/src/odoo/addons/web/controllers/main.py", line 959, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/komunigi/src/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/komunigi/src/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/komunigi/src/coopiteasy/vertical-cooperative/cooperator/wizard/create_subscription_from_partner.py", line 220, in create_subscription
    new_sub_req = sub_req.create(vals)
  File "<decorator-gen-273>", line 2, in create
  File "/home/komunigi/src/odoo/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/home/komunigi/src/coopiteasy/vertical-cooperative/cooperator/models/subscription_request.py", line 111, in create
    subscription_request = super(SubscriptionRequest, self).create(vals)
  File "<decorator-gen-116>", line 2, in create
  File "/home/komunigi/src/odoo/odoo/api.py", line 461, in _model_create_multi
    return create(self, [arg])
  File "/home/komunigi/src/odoo/addons/mail/models/mail_thread.py", line 272, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/home/komunigi/src/odoo/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/home/komunigi/src/odoo/odoo/models.py", line 3652, in create
    self.recompute()
  File "/home/komunigi/src/odoo/odoo/models.py", line 5322, in recompute
    vals = {n: rec[n] for n in ns}
  File "/home/komunigi/src/odoo/odoo/models.py", line 5322, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/home/komunigi/src/odoo/odoo/models.py", line 5169, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/komunigi/src/odoo/odoo/fields.py", line 1068, in __get__
    self.determine_value(record)
  File "/home/komunigi/src/odoo/odoo/fields.py", line 1157, in determine_value
    self.compute_value(recs)
  File "/home/komunigi/src/odoo/odoo/fields.py", line 1135, in compute_value
    self._compute_value(records)
  File "/home/komunigi/src/odoo/odoo/fields.py", line 1126, in _compute_value
    getattr(records, self.compute)()
  File "/home/komunigi/src/coopiteasy/vertical-cooperative/cooperator/models/subscription_request.py", line 149, in _compute_name
    sub_request.name = " ".join([self.firstname, self.lastname])
TypeError: sequence item 0: expected str instance, bool found
```

**Comment by carmenbianca** [comment]
Fixed by #293
