### ISSUE TITLE
Error when validating a company sub request related to an existing cooperator

### ISSUE THREAD

**Issue by victor-champonnois** [coopiteasy/vertical-cooperative#371]
Found by @polchampion in https://github.com/coopiteasy/vertical-cooperative/issues/350

Sur `lasource-test`, j'ai : 
- [x] créé une demande de souscitpion pour un partenaire 'test test' : le contact créé est une adresse de type contact --> ok
- [ ] créé une [demande de souscription](https://lasource.test.coopiteasy.be/web#id=122&action=480&model=subscription.request&view_type=form&menu_id=298) pour une société 'Société de test', avec comme coopérator 'test test' : j'ai une erreur copiée ci-dessous.

``` Server application error
 Error code: 200 
 Error message: Odoo Server Error 
 Error data message:
 Vous ne pouvez pas créer de hiérarchie de partenaires récursive.
None 
 Error data debug:
 Traceback (most recent call last):
  File "/home/odoo12/src/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo12/src/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo12/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo12/src/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo12/src/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo12/src/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo12/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo12/src/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/odoo12/src/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo12/src/odoo/addons/web/controllers/main.py", line 971, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo12/src/odoo/addons/web/controllers/main.py", line 959, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo12/src/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo12/src/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo12/src/coopiteasy/obeesdoo/beesdoo_easy_my_coop/models/subscription_request.py", line 42, in validate_subscription_request
    invoice = super().validate_subscription_request()[0]
  File "/home/odoo12/src/coopiteasy/vertical-cooperative/cooperator/models/subscription_request.py", line 760, in validate_subscription_request
    contact.write({"parent_id": partner.id, "representative": True})
  File "/home/odoo12/src/coopiteasy/obeesdoo/eater/models/partner.py", line 45, in write
    return super(Partner, self).write(values)
  File "/home/odoo12/src/coopiteasy/obeesdoo/beesdoo_shift/models/res_partner.py", line 166, in write
    result = super(ResPartner, self).write(vals)
  File "/home/odoo12/src/odoo/odoo/addons/base/models/res_partner.py", line 564, in write
    result = result and super(Partner, self).write(vals)
  File "/home/odoo12/src/odoo/addons/mail/models/mail_thread.py", line 321, in write
    result = super(MailThread, self).write(values)
  File "/home/odoo12/src/odoo/addons/mail/models/mail_activity.py", line 621, in write
    return super(MailActivityMixin, self).write(vals)
  File "/home/odoo12/src/odoo/odoo/models.py", line 3366, in write
    self._write(store_vals)
  File "/home/odoo12/src/odoo/odoo/models.py", line 3502, in _write
    self._validate_fields(vals)
  File "/home/odoo12/src/odoo/odoo/models.py", line 1128, in _validate_fields
    check(self)
  File "/home/odoo12/src/odoo/odoo/addons/base/models/res_partner.py", line 347, in _check_parent_id
    raise ValidationError(_('You cannot create recursive Partner hierarchies.'))
odoo.exceptions.ValidationError: ('Vous ne pouvez pas créer de hiérarchie de partenaires récursive.', None)```

**Comment by victor-champonnois** [comment]
@polchampion 
The error happens here https://github.com/coopiteasy/vertical-cooperative/blob/ab367066ab4f371d18ed437f04005d9ff7e59f23/cooperator/models/subscription_request.py#L760
 because it is writing to a contact a parent_id that is the same partner as the contact itself. (i.e. in this case contact = partner)
The contact on which we are writing the parent is searched using the email. In Pol's example, the email of the newly created company is the same as the parent cooperator email. 
If we change the email, the error no longer happens. Note that the issue is with the personnal email, not the company email.

**Comment by polchampion** [comment]
My mistake: The `subscription_request.partner_id` field "Coopérateur" must not be filled. It must only be filled if the candidate cooperator already has an odoo profile. So the error was to be expected. There is currently no way to select an existing representative for a company susciption request.
